### ISSUE TITLE
Back slot and trinket add-on

### ISSUE THREAD

**Issue by Ureiah** [MrCreativ3001/Good-Gravestones#4]
Is it possible to make it so back slot items and trinket items also drop into the graves as well? I have the mod on 1.19.2 fabric and i would like to see those items drop into the barrels as well. Thank you for your time! I love your mod.

**Comment by MrCreativ3001** [comment]
Hi there,
I think this would be a nice addition to the mod. I am going to try to implement support for both mods.

**Comment by Ureiah** [comment]
Thank you so much! I look forward to the next update!

**Comment by MrCreativ3001** [comment]
The version 1.1.0 on Curseforge drops trinkets and back slot items in the graves.
